version: '3'
services:
  spoty-fe:
    image: spoty-fe:v2
    container_name: spoty-fe
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    # restart: always
    ports:
      - 3000:3000

networks:
  default:
    name: spoty
    external: true